FROM nginx:latest


WORKDIR /usr/share/nginx/html
#change working directory to the root of nginx webhost
# using WORKDIR is prefer to using RUN cd /path because it is more readable

COPY index.html index.html

